#!/usr/bin/env ruby

require_relative '../lib/simulation'

# https://en.wikipedia.org/wiki/Birthday_problem

$n = ARGV[0]&.to_i || 23
$times = ARGV[1]&.to_i || 1_000

$s = Simulation.new do
  birthdays = Array.new($n) { rand(365.25) }
  birthdays.any? { |e| birthdays.count(e) > 1 }
end

$s.run_with_report($times)
