#!/usr/bin/env ruby

require_relative '../lib/simulation'

$times = ARGV.first&.to_i || 1_000_000
$s = Simulation.new { rand(2) == 0 }

puts 'Times: %i' % [$times]
puts 'Average: %0.0f%%' % [100 * $s.run($times)]
