#!/usr/bin/env ruby

# https://en.wikipedia.org/wiki/Prosecutor's_fallacy

require 'distribution'
require_relative '../lib/simulation'

$p = ARGV[0]&.to_i || 10_000_000
$times = ARGV[1]&.to_i || 10_000

$normal = Distribution::Normal.rng(1, 1)

$s = Simulation.new do
  x = $normal.call
  redo if x < 1
  e = x / 1_000_000

  ($p * e - 1) / ($p * e)
end

puts 'Population: %i' % [$p]
puts 'Times: %i' % [$times]
puts 'Average: %0.0f%%' % [100 * $s.run($times)]
q = $s.quantiles([0.25, 0.50, 0.75]).map { |e| e * 100 }
puts 'Cuartiles: %0.0f%%, %0.0f%%, %0.0f%%' % q
